{{ if and .Values.gcs_serviceaccount.enabled (not .Values.gcs_serviceaccount.existing_secret.enabled) -}}
apiVersion: v1
data:
  serviceaccount.json: {{ required "Private key for the service account is required" .Values.gcs_serviceaccount.privatekey | b64enc}}
kind: Secret
metadata:
  name: {{ .Chart.Name }}-serviceaccount-key
{{ end -}}